name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run one-line script
      run: go test ./...
    - name: Run more then one line script
      run: |
        echo "Line one"
        echo "Line two"
        make test
