name: CI

on: 
  push: 
    branches: 
    — master
    — staging
    — develop
  pull_request: 
    branches: 
    — master
    — staging
    — develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run more then one line script
      run: |
        go test ./...
