name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run one-line script
      run: echo "Test one line script"
    - name: Run more then one line script
      run: |
        echo "Run the tests"
        make test
    - name: Build docker image
      run: |
        echo "Build docker image"
        make docker_build